branches: master
language: node_js
node_js: v12
services: docker
addons:
  ssh_known_hosts: digitalleman.com
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in id_rsa.enc -out id_rsa -d
- docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
- npm install -g @lhci/cli@0.5.x
deploy:
  provider: script
  script: bash ci-deploy.sh
  cleanup: false
  skip_cleanup: true
after_deploy:
- lhci autorun
notifications:
  slack:
    secure: V1gGpN4MtRxkXp/YDzac3B1veDGOHxI4RIf5r+Z21HH0Df0tyYZJm7z8d51X0QuhFH+bKGQGEi4oeeDrC9hxPElVGJ8AksXcki95Go9cT5WpAjnIeUF9OUDk7v/qpoO9E5AGUrxJBuVGgdSqFD25K0RPssF1xIu4qROrY+EK4nnOFWgTzHntHyBu4wXLs+LYxRvoMMFYhoUly8C7ukVB97y30v8Aw1HSYoq/LDa4nvMuxqD5+Z+jHq9YYrlt0EVUXTkFvr5b6JDzGNhDKntVImvQokhpH6Cgs64hY5Vae2qvfb/tqPZhCc03Qa3lBO+dQISLd+yh7+2ItvZhbJOxjNGM4m0UURVCnRrfZ/1WvA/6yQN0D42JC/Qz97vJz19tnqYCToxPuh9xQjb0tO2xGoZYCyutvJ85dtB/uQ9Xslob7WOtD/8AEIfZ7E7sOkwgCZeWrirG6VpXZDXX9z7XIdHlW5jIndbtEdfZ9cpTA6fjVDVulEdJD+5XWrbmD7dFT0T96jNkatZWVfCpUaLlDd+xGdGnrmnDwl3ucf8Bu1w8WZmUQ3WdOMCT9WpEj/4IIbGs8T2oCBPQUjuVh1KosYOYFu9YQo7jp/lZdwOswDjo025lg1IHs8MXcYWoAEXAih0YAEuaL5fX35SdKrBeiRblMi6dpcwsl/ZmHboI/TU=
