apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reverse-proxy
  annotations:
    cert-manager.io/cluster-issuer: cert
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "500m"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.digitalleman.com
        - api.digitalleman.com
        - calendar.digitalleman.com
        - id.digitalleman.com
        - app.squirrel.li
        - design-system.digitalleman.com
        - digitalleman.com
        - www.digitalleman.com
        - quentinburgniard.com
        - www.quentinburgniard.com
      secretName: cert
  rules:
    - host: api.digitalleman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 80
    - host: calendar.digitalleman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: calendar
                port:
                  number: 80
    - host: id.digitalleman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: id
                port:
                  number: 80
    - host: app.squirrel.li
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: squirrelli
                port:
                  number: 80
    - host: valeriestauffer.ch
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: valerie
                port:
                  number: 80
    - host: design-system.digitalleman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: design-system
                port:
                  number: 80
    - host: digitalleman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-digitalleman
                port:
                  number: 80
    - host: quentinburgniard.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: portfolio-quentinburgniard
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: files
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /v5/private-files/$1
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - files.digitalleman.com
      secretName: cert
  rules:
    - host: files.digitalleman.com
      http:
        paths:
          - path: /([^/]+\.[^/]+)
            pathType: ImplementationSpecific
            backend:
              service:
                name: api
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal
  annotations:
    cert-manager.io/cluster-issuer: internal-cert
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/whitelist-source-range: "213.55.174.37/32"
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: internal-auth
    nginx.ingress.kubernetes.io/auth-realm: "Internal"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - db.internal.digitalleman.com
      secretName: internal-cert
  rules:
    - host: db.internal.digitalleman.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: db-admin
                port:
                  number: 80
