apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: ghcr.io/quentinburgniard/api:5.1.51
          env:
            - name: DB_HOST
              value: "db"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DB_PASSWORD
            - name: URL
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: API_URL
            - name: SALTS
              valueFrom:
                secretKeyRef:
                  name: env
                  key: API_SALTS
            - name: SECRETS
              valueFrom:
                secretKeyRef:
                  name: env
                  key: API_SECRETS
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: GEMINI_API_KEY
            - name: MAILGUN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: MAILGUN_API_KEY
            - name: FIXER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: FIXER_API_KEY
            - name: INFOMANIAK_URL
              valueFrom:
                secretKeyRef:
                  name: env
                  key: INFOMANIAK_URL
            - name: INFOMANIAK_BUCKET
              valueFrom:
                secretKeyRef:
                  name: env
                  key: INFOMANIAK_BUCKET
            - name: INFOMANIAK_ACCESS
              valueFrom:
                secretKeyRef:
                  name: env
                  key: INFOMANIAK_ACCESS
            - name: INFOMANIAK_SECRET
              valueFrom:
                secretKeyRef:
                  name: env
                  key: INFOMANIAK_SECRET
            - name: SENTRY_URL
              valueFrom:
                secretKeyRef:
                  name: env
                  key: SENTRY_URL
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
