apiVersion: v1
kind: Service
metadata:
  name: calendar
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: calendar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar
  template:
    metadata:
      labels:
        app: calendar
    spec:
      containers:
        - name: calendar
          image: ghcr.io/quentinburgniard/calendar:1.0.11
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: env
                  key: CALENDAR_API_KEY
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
