apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
    - name: mysql
      port: 3306
  clusterIP: None
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: mariadb
          image: mariadb:12.1.2
          env:
            - name: MARIADB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: DB_NAME
            - name: MARIADB_RANDOM_ROOT_PASSWORD
              value: "true"
            - name: MARIADB_USER
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DB_USER
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: env
                  key: DB_PASSWORD
          #ports:
          #  - name: mysql
          #    containerPort: 3306
          #readinessProbe:
          #  exec: { command: ["bash","-c","mysqladmin ping -u root -p$MARIADB_ROOT_PASSWORD"] }
          #  initialDelaySeconds: 10
          #  periodSeconds: 5
          #livenessProbe:
          #  exec: { command: ["bash","-c","mysqladmin ping -u root -p$MARIADB_ROOT_PASSWORD"] }
          #  initialDelaySeconds: 30
          #  periodSeconds: 10
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: db
              mountPath: /var/lib/mysql
      securityContext:
        fsGroup: 999
  volumeClaimTemplates:
    - metadata:
        name: db
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: db-admin
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: db-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-admin
  template:
    metadata:
      labels:
        app: db-admin
    spec:
      containers:
        - name: db-admin
          image: phpmyadmin:5.2.3
          env:
            - name: PMA_HOST
              value: "db"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
