apiVersion: v1
kind: Service
metadata:
  name: design-system
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: design-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: design-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: design-system
  template:
    metadata:
      labels:
        app: design-system
    spec:
      containers:
        - name: design-system
          image: ghcr.io/quentinburgniard/design-system:1.0.1
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
