apiVersion: v1
kind: Service
metadata:
  name: id
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: id
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: id
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id
  template:
    metadata:
      labels:
        app: id
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: id
          image: ghcr.io/quentinburgniard/id:0.0.26
          env:
            - name: COOKIE_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: COOKIE_DOMAIN
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: API_BASE_URL
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
