apiVersion: v1
kind: Service
metadata:
  name: squirrelli
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: squirrelli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squirrelli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squirrelli
  template:
    metadata:
      labels:
        app: squirrelli
    spec:
      containers:
        - name: squirrelli
          image: ghcr.io/quentinburgniard/squirrelli:0.0.16
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
