apiVersion: v1
kind: Service
metadata:
  name: squirelli
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: squirelli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squirelli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squirelli
  template:
    metadata:
      labels:
        app: squirelli
    spec:
      containers:
        - name: squirelli
          image: ghcr.io/quentinburgniard/penny:0.0.15
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
