apiVersion: v1
kind: Service
metadata:
  name: valerie
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: valerie
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: valerie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valerie
  template:
    metadata:
      labels:
        app: valerie
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: valerie
          image: ghcr.io/quentinburgniard/valerie:1.0.5
          env:
            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: API_BASE_URL
            - name: API_ID
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: VALERIE_API_ID
            - name: API_TOKEN
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: VALERIE_API_TOKEN
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
